"""UI strings for the built page. Interface languages: zh / en / es / ja."""

UI_LANGS = ["zh", "en", "es", "ja"]

UI_STRINGS = {
    "zh": {
        "langName": "中文",
        "hint": "点一下句子里带虚线的词查看词义；句尾按钮逐句朗读；词汇表和译文可展开。",
        "slow": "🐢 慢速跟读",
        "voiceEmbedded": "朗读：内嵌神经网络语音",
        "voiceSystem": "朗读：系统语音合成",
        "voiceNone": "⚠️ 此浏览器不支持朗读",
        "vocabList": "词汇表",
        "words": "词",
        "grammar": "语法点",
        "translation": "译文",
        "playAll": "▶ 整段",
        "stop": "■ 停止",
        "readSentence": "朗读这句",
        "coverage": "词表覆盖",
        "covered": "已覆盖",
        "uncoveredWords": "未覆盖的词",
        "allCovered": "🎉 词表已全部覆盖",
        "candidate": "备选",
        "storiesLabel": "故事",
        "home": "首页",
        "myBook": "我的故事书",
        "delStory": "删除这篇",
        "delConfirm": "再点一次确认删除",
        "restoreDemo": "恢复内置故事",
        "studyMode": "学习模式",
        "readTab": "阅读",
        "reviewTab": "复习",
        "reviewHint": "先回想词义，再翻面检查；复习进度会自动保存。",
        "reviewDue": "待复习",
        "reviewReviewed": "已复习",
        "reviewPrompt": "先在心里说出它的意思",
        "reviewSpeak": "朗读这个词",
        "reviewReveal": "显示答案",
        "reviewAnswerLabel": "填写它的中文或英文意思",
        "reviewAnswerPlaceholder": "例如：房子 或 house",
        "reviewAnswerHint": "输入一个常见释义即可，不区分英文大小写。",
        "reviewCheck": "检查答案",
        "reviewSkip": "直接看答案",
        "reviewCorrect": "回答正确",
        "reviewIncorrect": "暂时不对",
        "reviewYourAnswer": "你的答案",
        "reviewAgain": "没想起",
        "reviewHard": "旧版中间项",
        "reviewOther": "其他",
        "reviewOtherHint": "答案有问题",
        "reviewIssueSaved": "已记录到 Q&A，当前卡片尚未评分。",
        "reviewIssueFailed": "暂时无法记录，请稍后重试。",
        "reviewKnow": "想起来了",
        "reviewAgainTime": "本轮稍后再来",
        "reviewHardTime": "仅用于旧记录",
        "reviewInDays": "{n} 天后",
        "reviewExample": "例句",
        "reviewComplete": "这一轮完成",
        "reviewCompleteHint": "刚刚复习了 {n} 个词。",
        "reviewContinue": "继续下一轮",
        "reviewAllDone": "今天的复习已完成",
        "reviewAllDoneHint": "下一张卡片到期前，可以继续读故事。",
        "reviewNoWords": "还没有可复习的词",
        "reviewNoWordsHint": "导入词表后，词条会出现在这里。",
    },
    "en": {
        "langName": "English",
        "hint": "Tap a dotted word for its meaning; the button after each sentence reads it aloud; vocabulary and translation fold out.",
        "slow": "🐢 Slow",
        "voiceEmbedded": "Audio: embedded neural voice",
        "voiceSystem": "Audio: system speech synthesis",
        "voiceNone": "⚠️ This browser cannot speak",
        "vocabList": "Vocabulary",
        "words": "words",
        "grammar": "Grammar notes",
        "translation": "Translation",
        "playAll": "▶ Play all",
        "stop": "■ Stop",
        "readSentence": "Read this sentence",
        "coverage": "Vocabulary coverage",
        "covered": "covered",
        "uncoveredWords": "Uncovered words",
        "allCovered": "🎉 Whole vocabulary covered",
        "candidate": "Candidate",
        "storiesLabel": "stories",
        "home": "Home",
        "myBook": "My storybook",
        "delStory": "Delete this story",
        "delConfirm": "Click again to confirm",
        "restoreDemo": "Restore built-in stories",
        "studyMode": "Study mode",
        "readTab": "Read",
        "reviewTab": "Review",
        "reviewHint": "Recall the meaning first, then reveal the answer. Progress is saved automatically.",
        "reviewDue": "Due",
        "reviewReviewed": "Reviewed",
        "reviewPrompt": "Say the meaning before you reveal it",
        "reviewSpeak": "Hear this word",
        "reviewReveal": "Show answer",
        "reviewAnswerLabel": "Enter the meaning in Chinese or English",
        "reviewAnswerPlaceholder": "For example: 房子 or house",
        "reviewAnswerHint": "Enter one common meaning. English is not case-sensitive.",
        "reviewCheck": "Check answer",
        "reviewSkip": "Reveal instead",
        "reviewCorrect": "Correct",
        "reviewIncorrect": "Not quite",
        "reviewYourAnswer": "Your answer",
        "reviewAgain": "Missed it",
        "reviewHard": "Legacy middle option",
        "reviewOther": "Other",
        "reviewOtherHint": "Answer issue",
        "reviewIssueSaved": "Saved to Q&A. This card has not been rated yet.",
        "reviewIssueFailed": "Could not save this issue. Please try again.",
        "reviewKnow": "Got it",
        "reviewAgainTime": "later this round",
        "reviewHardTime": "legacy records only",
        "reviewInDays": "in {n} days",
        "reviewExample": "Example",
        "reviewComplete": "Round complete",
        "reviewCompleteHint": "You just reviewed {n} words.",
        "reviewContinue": "Continue reviewing",
        "reviewAllDone": "Today's review is complete",
        "reviewAllDoneHint": "Keep reading until the next card is due.",
        "reviewNoWords": "No words to review yet",
        "reviewNoWordsHint": "Import a vocabulary list and its entries will appear here.",
    },
    "es": {
        "langName": "Español",
        "hint": "Toca una palabra punteada para ver su significado; el botón tras cada frase la lee en voz alta; vocabulario y traducción se despliegan.",
        "slow": "🐢 Lento",
        "voiceEmbedded": "Audio: voz neuronal integrada",
        "voiceSystem": "Audio: síntesis de voz del sistema",
        "voiceNone": "⚠️ Este navegador no puede hablar",
        "vocabList": "Vocabulario",
        "words": "palabras",
        "grammar": "Notas de gramática",
        "translation": "Traducción",
        "playAll": "▶ Todo",
        "stop": "■ Parar",
        "readSentence": "Leer esta frase",
        "coverage": "Cobertura del vocabulario",
        "covered": "cubiertas",
        "uncoveredWords": "Palabras sin cubrir",
        "allCovered": "🎉 Vocabulario completo cubierto",
        "candidate": "Candidato",
        "storiesLabel": "historias",
        "home": "Inicio",
        "myBook": "Mi libro de cuentos",
        "delStory": "Eliminar esta historia",
        "delConfirm": "Pulsa otra vez para confirmar",
        "restoreDemo": "Restaurar historias integradas",
        "studyMode": "Modo de estudio",
        "readTab": "Leer",
        "reviewTab": "Repasar",
        "reviewHint": "Recuerda primero el significado y luego muestra la respuesta. El progreso se guarda automáticamente.",
        "reviewDue": "Pendientes",
        "reviewReviewed": "Repasadas",
        "reviewPrompt": "Di el significado antes de mostrarlo",
        "reviewSpeak": "Escuchar esta palabra",
        "reviewReveal": "Mostrar respuesta",
        "reviewAnswerLabel": "Escribe el significado en chino o inglés",
        "reviewAnswerPlaceholder": "Por ejemplo: 房子 o house",
        "reviewAnswerHint": "Escribe un significado habitual. No distingue mayúsculas en inglés.",
        "reviewCheck": "Comprobar",
        "reviewSkip": "Ver la respuesta",
        "reviewCorrect": "Correcto",
        "reviewIncorrect": "Todavía no",
        "reviewYourAnswer": "Tu respuesta",
        "reviewAgain": "No me acordé",
        "reviewHard": "Opción intermedia anterior",
        "reviewOther": "Otro",
        "reviewOtherHint": "Problema con la respuesta",
        "reviewIssueSaved": "Guardado en Q&A. Esta tarjeta aún no se ha evaluado.",
        "reviewIssueFailed": "No se pudo guardar. Inténtalo de nuevo.",
        "reviewKnow": "Me acordé",
        "reviewAgainTime": "más tarde en esta ronda",
        "reviewHardTime": "solo registros anteriores",
        "reviewInDays": "en {n} días",
        "reviewExample": "Ejemplo",
        "reviewComplete": "Ronda completada",
        "reviewCompleteHint": "Acabas de repasar {n} palabras.",
        "reviewContinue": "Seguir repasando",
        "reviewAllDone": "El repaso de hoy está completo",
        "reviewAllDoneHint": "Sigue leyendo hasta que toque la próxima tarjeta.",
        "reviewNoWords": "Aún no hay palabras para repasar",
        "reviewNoWordsHint": "Importa una lista y sus palabras aparecerán aquí.",
    },
    "ja": {
        "langName": "日本語",
        "hint": "点線の語をタップすると意味が表示されます。文末のボタンで音読、語彙表と訳文は展開できます。",
        "slow": "🐢 ゆっくり",
        "voiceEmbedded": "音声：内蔵ニューラル音声",
        "voiceSystem": "音声：システム音声合成",
        "voiceNone": "⚠️ このブラウザは音声非対応",
        "vocabList": "語彙表",
        "words": "語",
        "grammar": "文法ポイント",
        "translation": "訳文",
        "playAll": "▶ 全文",
        "stop": "■ 停止",
        "readSentence": "この文を読み上げる",
        "coverage": "語彙カバー率",
        "covered": "カバー済み",
        "uncoveredWords": "未カバーの語",
        "allCovered": "🎉 語彙を全てカバーしました",
        "candidate": "候補",
        "storiesLabel": "話",
        "home": "ホーム",
        "myBook": "わたしのストーリーブック",
        "delStory": "この話を削除",
        "delConfirm": "もう一度押して確認",
        "restoreDemo": "内蔵ストーリーを復元",
        "studyMode": "学習モード",
        "readTab": "読む",
        "reviewTab": "復習",
        "reviewHint": "まず意味を思い出してから答えを表示します。進捗は自動的に保存されます。",
        "reviewDue": "復習待ち",
        "reviewReviewed": "復習済み",
        "reviewPrompt": "答えを見る前に意味を思い出しましょう",
        "reviewSpeak": "この語を聞く",
        "reviewReveal": "答えを表示",
        "reviewAnswerLabel": "中国語または英語の意味を入力",
        "reviewAnswerPlaceholder": "例：房子 または house",
        "reviewAnswerHint": "一般的な意味を一つ入力してください。英語の大文字小文字は区別しません。",
        "reviewCheck": "答え合わせ",
        "reviewSkip": "答えを見る",
        "reviewCorrect": "正解",
        "reviewIncorrect": "まだ違います",
        "reviewYourAnswer": "あなたの答え",
        "reviewAgain": "思い出せなかった",
        "reviewHard": "旧バージョンの中間選択",
        "reviewOther": "その他",
        "reviewOtherHint": "答えに問題がある",
        "reviewIssueSaved": "Q&A に記録しました。このカードはまだ評価されていません。",
        "reviewIssueFailed": "記録できませんでした。もう一度お試しください。",
        "reviewKnow": "思い出せた",
        "reviewAgainTime": "この回でもう一度",
        "reviewHardTime": "旧記録のみ",
        "reviewInDays": "{n} 日後",
        "reviewExample": "例文",
        "reviewComplete": "今回の復習は完了",
        "reviewCompleteHint": "{n} 語を復習しました。",
        "reviewContinue": "次の復習へ",
        "reviewAllDone": "今日の復習は完了です",
        "reviewAllDoneHint": "次のカードまで、ストーリーを読み進めましょう。",
        "reviewNoWords": "まだ復習する語がありません",
        "reviewNoWordsHint": "単語リストを取り込むと、語彙がここに表示されます。",
    },
}
