"""UI strings for the built page. Interface languages: zh / en / es / ja."""

UI_LANGS = ["zh", "en", "es", "ja"]

UI_STRINGS = {
    "zh": {
        "langName": "中文",
        "hint": "点一下句子里带虚线的词查看词义；句尾按钮逐句朗读；词汇表和译文可展开。",
        "slow": "🐢 慢速跟读",
        "voiceEmbedded": "朗读：内嵌神经网络语音",
        "voiceSystem": "朗读：系统语音合成",
        "voiceNone": "⚠️ 此浏览器不支持朗读",
        "vocabList": "词汇表",
        "words": "词",
        "grammar": "语法点",
        "translation": "译文",
        "playAll": "▶ 整段",
        "stop": "■ 停止",
        "readSentence": "朗读这句",
        "coverage": "词表覆盖",
        "covered": "已覆盖",
        "uncoveredWords": "未覆盖的词",
        "allCovered": "🎉 词表已全部覆盖",
        "candidate": "备选",
        "storiesLabel": "故事",
        "home": "首页",
        "myBook": "我的故事书",
        "delStory": "删除这篇",
        "delConfirm": "再点一次确认删除",
    },
    "en": {
        "langName": "English",
        "hint": "Tap a dotted word for its meaning; the button after each sentence reads it aloud; vocabulary and translation fold out.",
        "slow": "🐢 Slow",
        "voiceEmbedded": "Audio: embedded neural voice",
        "voiceSystem": "Audio: system speech synthesis",
        "voiceNone": "⚠️ This browser cannot speak",
        "vocabList": "Vocabulary",
        "words": "words",
        "grammar": "Grammar notes",
        "translation": "Translation",
        "playAll": "▶ Play all",
        "stop": "■ Stop",
        "readSentence": "Read this sentence",
        "coverage": "Vocabulary coverage",
        "covered": "covered",
        "uncoveredWords": "Uncovered words",
        "allCovered": "🎉 Whole vocabulary covered",
        "candidate": "Candidate",
        "storiesLabel": "stories",
        "home": "Home",
        "myBook": "My storybook",
        "delStory": "Delete this story",
        "delConfirm": "Click again to confirm",
    },
    "es": {
        "langName": "Español",
        "hint": "Toca una palabra punteada para ver su significado; el botón tras cada frase la lee en voz alta; vocabulario y traducción se despliegan.",
        "slow": "🐢 Lento",
        "voiceEmbedded": "Audio: voz neuronal integrada",
        "voiceSystem": "Audio: síntesis de voz del sistema",
        "voiceNone": "⚠️ Este navegador no puede hablar",
        "vocabList": "Vocabulario",
        "words": "palabras",
        "grammar": "Notas de gramática",
        "translation": "Traducción",
        "playAll": "▶ Todo",
        "stop": "■ Parar",
        "readSentence": "Leer esta frase",
        "coverage": "Cobertura del vocabulario",
        "covered": "cubiertas",
        "uncoveredWords": "Palabras sin cubrir",
        "allCovered": "🎉 Vocabulario completo cubierto",
        "candidate": "Candidato",
        "storiesLabel": "historias",
        "home": "Inicio",
        "myBook": "Mi libro de cuentos",
        "delStory": "Eliminar esta historia",
        "delConfirm": "Pulsa otra vez para confirmar",
    },
    "ja": {
        "langName": "日本語",
        "hint": "点線の語をタップすると意味が表示されます。文末のボタンで音読、語彙表と訳文は展開できます。",
        "slow": "🐢 ゆっくり",
        "voiceEmbedded": "音声：内蔵ニューラル音声",
        "voiceSystem": "音声：システム音声合成",
        "voiceNone": "⚠️ このブラウザは音声非対応",
        "vocabList": "語彙表",
        "words": "語",
        "grammar": "文法ポイント",
        "translation": "訳文",
        "playAll": "▶ 全文",
        "stop": "■ 停止",
        "readSentence": "この文を読み上げる",
        "coverage": "語彙カバー率",
        "covered": "カバー済み",
        "uncoveredWords": "未カバーの語",
        "allCovered": "🎉 語彙を全てカバーしました",
        "candidate": "候補",
        "storiesLabel": "話",
        "home": "ホーム",
        "myBook": "わたしのストーリーブック",
        "delStory": "この話を削除",
        "delConfirm": "もう一度押して確認",
    },
}
